name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # This line removes the warning you just received
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Deepti-singh-196:$HF_TOKEN@huggingface.co/spaces/Deepti-singh-196/LawAssit_Version1_RAG main
